name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Commit changes
      run: |
        git config user.name "pedrohenrique57"
        git config user.email "pedro.henrique.contato369@gmail.com"
        git add .
        git commit -m "Automated commit"

    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
